# Generated by Django 5.1 on 2025-03-20 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arquivopdf',
            options={'verbose_name': 'Arquivo PDF', 'verbose_name_plural': 'Arquivos PDF'},
        ),
        migrations.AlterField(
            model_name='arquivopdf',
            name='nome',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome do Arquivo'),
        ),
        migrations.AlterField(
            model_name='arquivopdf',
            name='pdf',
            field=models.FileField(upload_to='pdfs/', verbose_name='Arquivo PDF'),
        ),
        migrations.CreateModel(
            name='Ata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('serie', models.CharField(choices=[('1', '1º ano'), ('2', '2º ano'), ('3', '3º ano'), ('4', '4º ano'), ('5', '5º ano'), ('6', '6º ano')], max_length=50, verbose_name='Série')),
                ('turma', models.CharField(choices=[('A', 'Turma A'), ('B', 'Turma B'), ('C', 'Turma C'), ('D', 'Turma D'), ('E', 'Turma E'), ('F', 'Turma F')], max_length=50, verbose_name='Turma')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='atas/', verbose_name='Arquivo PDF')),
            ],
            options={
                'verbose_name': 'Ata',
                'verbose_name_plural': 'Atas',
                'unique_together': {('ano', 'serie', 'turma')},
            },
        ),
        migrations.AlterField(
            model_name='arquivopdf',
            name='ata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='ata.ata', verbose_name='Ata Relacionada'),
        ),
        migrations.DeleteModel(
            name='Atas',
        ),
    ]
