# Generated by Django 5.1 on 2025-03-20 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('num', models.IntegerField()),
                ('complemento', models.TextField(blank=True, null=True)),
                ('cidade', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=9)),
                ('estado', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('pdf', models.FileField(upload_to='pdfs/')),
                ('tipo_pessoa', models.CharField(choices=[('ALUNO', 'Aluno'), ('PROFESSOR', 'Professor')], default='ALUNO', max_length=10, verbose_name='Tipo de Pessoa')),
                ('endereco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to='pessoa.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='ArquivoPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='pdfs/')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='pessoa.pessoa')),
            ],
        ),
    ]
