# Generated by Django 5.1 on 2025-03-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arquivopdf',
            options={'ordering': ['pessoa__nome'], 'verbose_name': 'Arquivo PDF', 'verbose_name_plural': 'Arquivos PDF'},
        ),
        migrations.AlterModelOptions(
            name='endereco',
            options={'ordering': ['cidade', 'bairro', 'rua'], 'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
        migrations.AlterModelOptions(
            name='pessoa',
            options={'ordering': ['nome'], 'verbose_name': 'Pessoa', 'verbose_name_plural': 'Pessoas'},
        ),
        migrations.AddConstraint(
            model_name='pessoa',
            constraint=models.UniqueConstraint(fields=('cpf',), name='unique_cpf_pessoa'),
        ),
        migrations.AlterModelTable(
            name='arquivopdf',
            table='arquivos_pdf',
        ),
        migrations.AlterModelTable(
            name='endereco',
            table='enderecos',
        ),
        migrations.AlterModelTable(
            name='pessoa',
            table='pessoas',
        ),
    ]
